### ISSUE TITLE
SHT85 library for Particle Argon

### ISSUE THREAD

**Issue by nancyymn** [Sensirion/arduino-sht#14]
I am trying to work the SHT-85 library that was developed for Arduino in Particle Argon. However, the function .readSample() does not work after I tried many ways to fix it. I was wondering, would it be possible that the Sensirion’s technical support could fix the library for Particle? SPS30 does have an uploaded library in Particle and it helps tons of beginners.

Thank you!

**Comment by winkj** [comment]
Thanks for letting us know about the issues with this library; I don't currently have access to a board, but will add this to our requested platforms list

**Comment by nancyymn** [comment]
Thank you for your help in advance!
