### ISSUE TITLE
[Problem]: sht31D not updated regularly when used on Arduino nano

### ISSUE THREAD

**Issue by hasenradball** [Sensirion/arduino-sht#22]
Hello,

I used the example code on my Arduino Nano an call the getTermperature() + getHumidity() ervery 2 s.
But the Sensor values are never updated.
The Sensor was found on the Bus but, the values are not updated every period.

Is there an known Issue with the latest release?

**Comment by winkj** [comment]
Are you using the unmodified example? `getTemperature()` and `getHumidity()` don't update the data, that's done by `readSample()` only; so if you're not calling `readSample()`, the behaviour described is correct.

See https://github.com/Sensirion/arduino-sht/blob/master/examples/sht-autodetect/sht-autodetect.ino#L28

**Comment by hasenradball** [comment]
Oh my god,
I am sorry for this silly question.
sure I forgot the `readSample()` call 👎 

Thanks for your fast reply :+1
Frank...
