### ISSUE TITLE
Heater on SHT4x / SHT85 and status register on SHT48?

### ISSUE THREAD

**Issue by LukeSkaff** [Sensirion/arduino-sht#31]
Is there plans to support the heater on the SHT4x and SHT85?  Also reading the status register on the SHT85 would be nice as well.

**Comment by LeonieFierz** [comment]
Thank you for contacting us.
Please have a look at the SHT4x specific library which has support to activate the heater option for SHT4x.
For SHT85 please use https://github.com/Sensirion/arduino-i2c-sht3x as SHT3x has the same interface as the SHT85. This driver has support for the heater and status register.
